<?php

/** @var \TrainningVivek\PopupLogin\Block\Form\Forgotpassword $block */
?>
<style>
    .customer-popup-register {
        display: none;
    }
</style>
<div id="customer-popup-forgot-password" class="customer-popup-forgot-password">
    <form class="form password forget form-forger-password"
          action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'>
        <input type="hidden" name="redirect_url" value="<?php echo $this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]); ?>" />
        <div class="messages"></div>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
            <div class="field email required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
            </div>
            <div class="or-another-selection"><?php echo __('or'); ?></div>
            <div class="secondary"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>" id="customer-popup-sign-in"><span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span></a></div>
        </div>
    </form>
    <script type="text/x-magento-init">
        {
            "#customer-popup-forgot-password": {
                "TrainningVivek_PopupLogin/js/action/customer-authentication-popup": {
                    "popupTitle": "<?php /* @escapeNotVerified */ echo __('Forgot Password'); ?>",
                    "innerWidth": "600"
                }
            }
        }
    </script>
</div>
