<?php



?>

<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components": {
					"mutator": {
						"component":"SimplifiedMagento_HelloWorld/js/value-mutator",
						"template":"SimplifiedMagento_HelloWorld/button",
						"children": {
							"display" : {
								"component":"SimplifiedMagento_HelloWorld/js/value-display",
								"template":"SimplifiedMagento_HelloWorld/display"
							}
						}
					}
				}
			} 
		}
	}
</script>

<div data-bind="scope: 'mutator'">
	<!-- ko template: getTemplate() -->
	<!-- /ko -->
</div>

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components": {
					"exampleUiComponent": {
						"component":"SimplifiedMagento_HelloWorld/js/ui-component",
						"template":"SimplifiedMagento_HelloWorld/localize-template"
					}
				}
			} 
		}
	}
</script>-->

<!--<div data-bind="scope: 'exampleUiComponent'">-->
	
<!--</div>-->

<!-- shared component -->

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app": {
				"components": {
					"root" : {
						"component": "SimplifiedMagento_HelloWorld/js/root",
						"deps":["root.sharedState"],
						"children": {
							"sharedState": {
								"component":"SimplifiedMagento_HelloWorld/js/shared-state"
							}
						}
					}
				}
			}
		}
	}
</script>

<div data-bind="scope: 'root'">
	<div>
		The Value is:
		<span data-bind="text: value"></span>
	</div>
</div>-->
<!--<script type="text/x-magento-init">
	{
		"#target":{
			"coffee":{
				"base_url":"<?//= $block->escapeJs($block->getBaseUrl()) ?>"
			} 
		}
	}
</script>-->
<!--<div id="target" data-mage-init='{"SimplifiedMagento_HelloWorld/js/requirejs-example":{"base_url":"/"}}'></div>-->
<!--<div id="target"></div>-->
<!--<h1 data-mage-init='{"simplifiedMagento/title":{}}' />
<h1 data-mage-init='{"simplifiedMagento-title":{}}' />-->

<!--<form data-mage-init='{"validation": {}}'>
	<div class="control">
		<input type="text" name="email" id="email" class="input-text" placeholder="<?//= __('Your Email') ?>" data-validate="{required:true, 'validate-email': true}" />
	</div>
	<button type="submit" class="action primary"><?//= __('Submit') ?></button>
</form>-->

<!--<div id="my-collapsible" data-mage-init='{"SimplifiedMagento_HelloWorld/js/dynamic-collapsible": {"ajaxContent":true}}'>
	<div data-role="title">
		<h2>How about a collapsible widget<button data-role="trigger">GO</button></h2>
	</div>
	<div id="example" data-role="content">
	</div>
	<a href="<?//= $block->getViewFileUrl('SimplifiedMagento_HelloWorld/example-content.html') ?>" data-ajax="true"></a>
</div>-->

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components": {
					"exampleUiComponent": {
						"component":"SimplifiedMagento_HelloWorld/js/ui-component-a",
						"provider":"exampleUiComponentB",
						"providerProperty": "value"
					},
					"exampleUiComponentB": {
						"component":"SimplifiedMagento_HelloWorld/js/ui-component-b"
					}
				}
			} 
		}
	}
</script>-->

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app": <?//= $block->getJsLayout() ?>
		}
	}
</script>

<div data-bind="scope: 'exampleUiComponent'">
	<h3 data-bind="text: label"></h3>
	<div data-bind="text: amount"></div>

	<div data-bind="with: getChild('exampleUiComponentB')">
		<h3 data-bind="text: title"></h3>
		<div data-bind="text: value"></div>
	</div>
</div>-->

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components": {
					"startSimple": {
						"component":"SimplifiedMagento_HelloWorld/js/plain-view-model",
						"base_url":"<?//= $block->escapeJs($block->getBaseUrl()) ?>"
					}
				}
			} 
		}
	}
</script>-->

<!--<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app":{
				"components": {
					"exampleUiComponent": {
						"component":"uiComponent",
						"children":{
							"child1": {
								"component":"uiComponent",
								"template":"SimplifiedMagento_HelloWorld/info",
								"displayArea":"groupA"
							},
							"child2": {
								"component":"uiComponent",
								"template":"SimplifiedMagento_HelloWorld/info",
								"displayArea":"groupB"
							}
						}
					}
				}
			} 
		}
	}
</script>-->

<!--<div data-bind="scope: 'exampleUiComponent'">-->
	
<!--</div>-->
<!--<div data-bind="scope: 'startSimple'">
	<h2 data-bind="text: label"></h2>
	<table data-bind="foreach: items">
		 <tr>
			<td data-bind="text: name"></td>
			<td data-bind="text: qty"></td>
			<td data-bind="text: price"></td>
			<td data-bind="text: $parent.rowTotal($data)"></td>
		</tr>
	</table>
	<div>Additional change: <span data-bind="text: additional_change"></span></div>
	<strong>Total: <span data-bind="text: total()"></span></strong>-->
	<!--<h2 data-bind="text: title"></h2>
	<pre data-bind="text: JSON.stringify(config, null, 2)"></pre>-->
	<!--<pre data-bind="text: output"></pre>-->
	<!--<table data-bind="foreach: exchange_rates">
		<tr>
			<th data-bind="i18n: 'Currency to'"></th>
			<th data-bind="i18n: 'Rate'"></th>
		</tr>
		 ko foreach: exchange_rate -->
		<!-- <tr>
			<td data-bind="text: currency_to"></td>
			<td data-bind="text: rate"></td>
		</tr></table>-->
		<!-- /ko -->
	<!--<ui data-bind="foreach: values">
		<li data-bind="text: $data"></li>
	</ui>
</div>-->

<!--Stateful component<script type="text/x-magento-init">
	{
		"*":{
			"Magento_Ui/js/core/app": {
				"components": {
					"stateful-example-component" : {
						"component": "SimplifiedMagento_HelloWorld/js/stateful-example"
					}
				}
			}
		}
	}
</script>

<div data-bind="scope: 'stateful-example-component'">
	<h3>Your Input:</h3>
	<input data-bind="textInput: input" autofocus/>
</div>-->