<?php
	$product = $block->getProduct();
?>
<div id="daily-deals">
	<?php if ($product->getData('deal_status') == 1): ?>
		<h1 style="color: #1979c3">
			<?php echo date('d-m-Y H:i:s', time()); ?>
			<?php echo $product->getData('deal_time'); ?>
		</h1>
		<div class="countdown countdown-container container" id="daily-deals-counter">
		    <div class="clock row">
		        <div class="clock-item clock-days countdown-time-value col-sm-6 col-md-3">
		            <div class="wrap">
		                <div class="inner">
		                    <div id="canvas-days" class="clock-canvas"></div>

		                    <div class="text">
		                        <p class="val">0</p>
		                        <p class="type-days type-time">DAYS</p>
		                    </div><!-- /.text -->
		                </div><!-- /.inner -->
		            </div><!-- /.wrap -->
		        </div><!-- /.clock-item -->

		        <div class="clock-item clock-hours countdown-time-value col-sm-6 col-md-3">
		            <div class="wrap">
		                <div class="inner">
		                    <div id="canvas-hours" class="clock-canvas"></div>

		                    <div class="text">
		                        <p class="val">0</p>
		                        <p class="type-hours type-time">HOURS</p>
		                    </div><!-- /.text -->
		                </div><!-- /.inner -->
		            </div><!-- /.wrap -->
		        </div><!-- /.clock-item -->

		        <div class="clock-item clock-minutes countdown-time-value col-sm-6 col-md-3">
		            <div class="wrap">
		                <div class="inner">
		                    <div id="canvas-minutes" class="clock-canvas"></div>

		                    <div class="text">
		                        <p class="val">0</p>
		                        <p class="type-minutes type-time">MINUTES</p>
		                    </div><!-- /.text -->
		                </div><!-- /.inner -->
		            </div><!-- /.wrap -->
		        </div><!-- /.clock-item -->

		        <div class="clock-item clock-seconds countdown-time-value col-sm-6 col-md-3">
		            <div class="wrap">
		                <div class="inner">
		                    <div id="canvas-seconds" class="clock-canvas"></div>

		                    <div class="text">
		                        <p class="val">0</p>
		                        <p class="type-seconds type-time">SECONDS</p>
		                    </div><!-- /.text -->
		                </div><!-- /.inner -->
		            </div><!-- /.wrap -->
		        </div><!-- /.clock-item -->
		    </div><!-- /.clock -->
		</div><!-- /.countdown-wrapper -->
		<script type="text/x-magento-init">
		    {
		        "#daily-deals": {
		            "TrainningVivek_ProductDailyDeal/js/action/daily-deals-counter": {
		                "deal_time": "<?php /* @escapeNotVerified */ echo strtotime($product->getData('deal_time')); ?>"
		            }
		        }
		    }
		</script>
	<?php else: ?>
		<h1 style="color: #1979c3">
			Currently No Active Deal
		</h1>
	<?php endif; ?>
</div>